# Site settings
title: 前端流浪者
url: "https://lipinghai.cn"   
baseurl: "" 
description: >
  尘世间一个迷途书童
# Your information
email: leepinghai@gmail.com
author: 李平海
authorEn: LiPinghai
avatar: "//f2e.yy.com/s/activity/huya/avatar.jpg"
profile: 尘世间一个迷途书童
company: Tencent
location: Ontario, Canada
record: 粤ICP备2023147381号-1
#twitter_username: twitter_username
#github_username:  lipinghai
profile_links:
  Email: "mailto:leepinghai@gmail.com"
  GitHub: "https://github.com/LiPinghai"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

google_analytics: UA-135381641-1

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    首页: /
    归档: /category/
    关于本站: /about/

# permalink: /:title/
permalink: /:path/

plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji
 - jekyll-sitemap
 - jekyll-multiple-languages-plugin

languages: 
  en: "English"
  zh: "中文" 

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
